# Generated by Django 5.1.5 on 2025-04-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
