# Generated by Django 5.1.5 on 2025-04-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_tags_rename_content_post_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
