# Generated by Django 5.1.5 on 2025-04-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_categories_remove_post_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
